# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plottype1.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = mplwidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2.addWidget(self.widget)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.downBut = QtWidgets.QPushButton(self.frame_3)
        self.downBut.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downBut.sizePolicy().hasHeightForWidth())
        self.downBut.setSizePolicy(sizePolicy)
        self.downBut.setMinimumSize(QtCore.QSize(30, 30))
        self.downBut.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downBut.setIcon(icon)
        self.downBut.setObjectName("downBut")
        self.horizontalLayout_5.addWidget(self.downBut)
        self.upBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upBut.sizePolicy().hasHeightForWidth())
        self.upBut.setSizePolicy(sizePolicy)
        self.upBut.setMinimumSize(QtCore.QSize(30, 30))
        self.upBut.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upBut.setIcon(icon1)
        self.upBut.setObjectName("upBut")
        self.horizontalLayout_5.addWidget(self.upBut)
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.PeaksBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PeaksBut.sizePolicy().hasHeightForWidth())
        self.PeaksBut.setSizePolicy(sizePolicy)
        self.PeaksBut.setMinimumSize(QtCore.QSize(30, 30))
        self.PeaksBut.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("PlotP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PeaksBut.setIcon(icon2)
        self.PeaksBut.setObjectName("PeaksBut")
        self.horizontalLayout_5.addWidget(self.PeaksBut)
        self.RemBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemBut.sizePolicy().hasHeightForWidth())
        self.RemBut.setSizePolicy(sizePolicy)
        self.RemBut.setMinimumSize(QtCore.QSize(30, 30))
        self.RemBut.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("RemP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RemBut.setIcon(icon3)
        self.RemBut.setObjectName("RemBut")
        self.horizontalLayout_5.addWidget(self.RemBut)
        self.RanBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RanBut.sizePolicy().hasHeightForWidth())
        self.RanBut.setSizePolicy(sizePolicy)
        self.RanBut.setMinimumSize(QtCore.QSize(30, 30))
        self.RanBut.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("RanP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RanBut.setIcon(icon4)
        self.RanBut.setObjectName("RanBut")
        self.horizontalLayout_5.addWidget(self.RanBut)
        self.line_2 = QtWidgets.QFrame(self.frame_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.lenghBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lenghBut.sizePolicy().hasHeightForWidth())
        self.lenghBut.setSizePolicy(sizePolicy)
        self.lenghBut.setMinimumSize(QtCore.QSize(30, 30))
        self.lenghBut.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("lenght.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lenghBut.setIcon(icon5)
        self.lenghBut.setObjectName("lenghBut")
        self.horizontalLayout_5.addWidget(self.lenghBut)
        self.angleBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angleBut.sizePolicy().hasHeightForWidth())
        self.angleBut.setSizePolicy(sizePolicy)
        self.angleBut.setMinimumSize(QtCore.QSize(30, 30))
        self.angleBut.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("angle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.angleBut.setIcon(icon6)
        self.angleBut.setObjectName("angleBut")
        self.horizontalLayout_5.addWidget(self.angleBut)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.frame_Int = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Int.sizePolicy().hasHeightForWidth())
        self.frame_Int.setSizePolicy(sizePolicy)
        self.frame_Int.setMinimumSize(QtCore.QSize(400, 45))
        self.frame_Int.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Int.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Int.setObjectName("frame_Int")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_Int)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_Int)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_Int)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_Int)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 0))
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_3.addWidget(self.lcdNumber)
        self.verticalLayout.addWidget(self.frame_Int)
        self.frame_dist = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_dist.sizePolicy().hasHeightForWidth())
        self.frame_dist.setSizePolicy(sizePolicy)
        self.frame_dist.setMinimumSize(QtCore.QSize(400, 45))
        self.frame_dist.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dist.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dist.setObjectName("frame_dist")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_dist)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_25 = QtWidgets.QLabel(self.frame_dist)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_9.addWidget(self.label_25)
        self.horizontalSlider_12 = QtWidgets.QSlider(self.frame_dist)
        self.horizontalSlider_12.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_12.setObjectName("horizontalSlider_12")
        self.horizontalLayout_9.addWidget(self.horizontalSlider_12)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame_dist)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout_9.addWidget(self.lcdNumber_2)
        self.verticalLayout.addWidget(self.frame_dist)
        self.frame_rad = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_rad.sizePolicy().hasHeightForWidth())
        self.frame_rad.setSizePolicy(sizePolicy)
        self.frame_rad.setMinimumSize(QtCore.QSize(400, 45))
        self.frame_rad.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rad.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rad.setObjectName("frame_rad")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_rad)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.frame_rad)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.horizontalSlider_4 = QtWidgets.QSlider(self.frame_rad)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_4)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.frame_rad)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.horizontalLayout_4.addWidget(self.lcdNumber_3)
        self.verticalLayout.addWidget(self.frame_rad)
        self.frame_Sym = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Sym.sizePolicy().hasHeightForWidth())
        self.frame_Sym.setSizePolicy(sizePolicy)
        self.frame_Sym.setMinimumSize(QtCore.QSize(400, 45))
        self.frame_Sym.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Sym.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Sym.setObjectName("frame_Sym")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_Sym)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.frame_Sym)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.horizontalSlider_6 = QtWidgets.QSlider(self.frame_Sym)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalLayout_6.addWidget(self.horizontalSlider_6)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.frame_Sym)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.horizontalLayout_6.addWidget(self.lcdNumber_4)
        self.verticalLayout.addWidget(self.frame_Sym)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 337, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_contrast = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_contrast.sizePolicy().hasHeightForWidth())
        self.frame_contrast.setSizePolicy(sizePolicy)
        self.frame_contrast.setMinimumSize(QtCore.QSize(400, 45))
        self.frame_contrast.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contrast.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contrast.setObjectName("frame_contrast")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_contrast)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.frame_contrast)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.horizontalSlider_8 = QtWidgets.QSlider(self.frame_contrast)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.horizontalLayout_7.addWidget(self.horizontalSlider_8)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.frame_contrast)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.horizontalLayout_7.addWidget(self.lcdNumber_5)
        self.verticalLayout.addWidget(self.frame_contrast)
        self.frame_3D = QtWidgets.QFrame(self.frame_3)
        self.frame_3D.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3D.setObjectName("frame_3D")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3D)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.frame_3D)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.frame_3D)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.frame_3D)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_8.addWidget(self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.frame_3D)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_3D)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_8.addWidget(self.spinBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.frame_3D)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_8.addWidget(self.checkBox)
        self.verticalLayout.addWidget(self.frame_3D)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.frame_Int.setToolTip(_translate("MainWindow", "<html><head/><body><p>Intensity</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Int"))
        self.label_25.setText(_translate("MainWindow", "dist"))
        self.label_9.setText(_translate("MainWindow", "rad"))
        self.label_13.setText(_translate("MainWindow", "sym"))
        self.pushButton_2.setText(_translate("MainWindow", "Apply to all"))
        self.label_17.setText(_translate("MainWindow", "Int"))
        self.pushButton.setText(_translate("MainWindow", "create 3D"))
        self.label.setText(_translate("MainWindow", "px"))
        self.label_2.setText(_translate("MainWindow", "ref"))
        self.checkBox.setText(_translate("MainWindow", "Optimize \n"
" scale"))
from mplwidget import mplwidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
