# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plottype1.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets




class   SeqImaPlot(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = mplwidget(self.frame_2)
        self.widget.canvas.setMinimumSize(QtCore.QSize(600, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2.addWidget(self.widget)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.downBut = QtWidgets.QPushButton(self.frame_3)
        self.downBut.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downBut.sizePolicy().hasHeightForWidth())
        self.downBut.setText("")
        self.downBut.setIcon(QtGui.QIcon("down.png"))
        self.downBut.setObjectName("downBut")
        self.horizontalLayout_5.addWidget(self.downBut)
        self.upBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upBut.sizePolicy().hasHeightForWidth())
        self.upBut.setSizePolicy(sizePolicy)
        self.upBut.setMinimumSize(QtCore.QSize(30, 30))
        self.upBut.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upBut.setIcon(icon1)
        self.upBut.setObjectName("upBut")
        self.horizontalLayout_5.addWidget(self.upBut)
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.PeaksBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PeaksBut.sizePolicy().hasHeightForWidth())
        self.PeaksBut.setSizePolicy(sizePolicy)
        self.PeaksBut.setMinimumSize(QtCore.QSize(30, 30))
        self.PeaksBut.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("PlotP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PeaksBut.setIcon(icon2)
        self.PeaksBut.setObjectName("PeaksBut")
        self.horizontalLayout_5.addWidget(self.PeaksBut)
        self.RemBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemBut.sizePolicy().hasHeightForWidth())
        self.RemBut.setSizePolicy(sizePolicy)
        self.RemBut.setMinimumSize(QtCore.QSize(30, 30))
        self.RemBut.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("RemP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RemBut.setIcon(icon3)
        self.RemBut.setObjectName("RemBut")
        self.horizontalLayout_5.addWidget(self.RemBut)
        self.RanBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RanBut.sizePolicy().hasHeightForWidth())
        self.RanBut.setSizePolicy(sizePolicy)
        self.RanBut.setMinimumSize(QtCore.QSize(30, 30))
        self.RanBut.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("RanP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RanBut.setIcon(icon4)
        self.RanBut.setObjectName("RanBut")
        self.horizontalLayout_5.addWidget(self.RanBut)
        self.line_2 = QtWidgets.QFrame(self.frame_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.lenghBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lenghBut.sizePolicy().hasHeightForWidth())
        self.lenghBut.setSizePolicy(sizePolicy)
        self.lenghBut.setMinimumSize(QtCore.QSize(30, 30))
        self.lenghBut.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("lenght.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lenghBut.setIcon(icon5)
        self.lenghBut.setObjectName("lenghBut")
        self.horizontalLayout_5.addWidget(self.lenghBut)
        self.angleBut = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angleBut.sizePolicy().hasHeightForWidth())
        self.angleBut.setSizePolicy(sizePolicy)
        self.angleBut.setMinimumSize(QtCore.QSize(30, 30))
        self.angleBut.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("angle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.angleBut.setIcon(icon6)
        self.angleBut.setObjectName("angleBut")
        self.horizontalLayout_5.addWidget(self.angleBut)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.frame_Int = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Int.sizePolicy().hasHeightForWidth())

        # Sliders
        self.Int_sl = C3_slider(self.frame_3, self.verticalLayout, 'Inte')
        self.dist_sl = C3_slider(self.frame_3, self.verticalLayout, 'Dist') 
        self.rad_sl = C3_slider(self.frame_3, self.verticalLayout, 'Radi') 
        self.sym_sl = C3_slider(self.frame_3, self.verticalLayout, 'Symm') 

        self.applyalButton = QtWidgets.QPushButton(self.frame_3)
        self.applyalButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.applyalButton.setObjectName("applyalButton")
        self.verticalLayout.addWidget(self.applyalButton)

        spacerItem = QtWidgets.QSpacerItem(20, 337, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_contrast = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_contrast.sizePolicy().hasHeightForWidth())
        self.frame_contrast.setSizePolicy(sizePolicy)
        self.frame_contrast.setMinimumSize(QtCore.QSize(400, 45))
        self.frame_contrast.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contrast.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contrast.setObjectName("frame_contrast")

        self.vmax_sl = C3_slider(self.frame_contrast, self.verticalLayout, 'Contrast') 

        self.frame_3D = QtWidgets.QFrame(self.frame_3)
        self.frame_3D.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3D.setObjectName("frame_3D")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3D)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.frame_3D)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.frame_3D)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.frame_3D)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_8.addWidget(self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.frame_3D)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_3D)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_8.addWidget(self.spinBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.frame_3D)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_8.addWidget(self.checkBox)
        self.verticalLayout.addWidget(self.frame_3D)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.frame_Int.setToolTip(_translate("MainWindow", "<html><head/><body><p>Intensity</p></body></html>"))
        self.applyalButton.setText(_translate("MainWindow", "Apply to all"))
        self.pushButton.setText(_translate("MainWindow", "create 3D"))
        self.label.setText(_translate("MainWindow", "px"))
        self.label_2.setText(_translate("MainWindow", "ref"))
        self.checkBox.setText(_translate("MainWindow", "Optimize \n"
" scale"))
from .mplwidget import mplwidget, C3_slider


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = SeqImaPlot()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
