{% set name = "TEMpcPlot" %}
{% set version = "1.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Prestipino/TEMpcPlot.git
  git_rev: v1.4.2
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

extra:
  channels:
    - conda-forge

requirements:
  build:
    - python

  host:
    - pip
    - python
  run:
    - python >=3.8
    - scipy
    - numpy
    - matplotlib >=3.5.3, <3.7
    - scipy
    - pillow
    - uncertainties 
    - keyboard   
    - conda-forge::mplcursors

test:
  import:
  - TEMpcPlot

about:
  license: MIT
  license_family: BSD
  summary: testiasmo il packaging